INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, PAIS_NACIMIENTO, ESTADO) VALUES ('PEREZ', '1', 'ROBERTO', '093939393', 'CR', true);
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, PAIS_NACIMIENTO, ESTADO) VALUES ('SANCHEZ', '2', 'RAUL', '093223333', 'CR', false);
